// <auto-generated />
using System;
using Hjalpmedelskollen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hjalpmedelskollen.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240408082124_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hjalpmedelskollen.Models.AidModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("Inspection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<bool>("QrCode")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Registered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.Property<int?>("UnitModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UnitModelId");

                    b.ToTable("Aids");
                });

            modelBuilder.Entity("Hjalpmedelskollen.Models.InstitutionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("Hjalpmedelskollen.Models.UnitModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer");

                    b.Property<int?>("InstitutionModelId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionModelId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Hjalpmedelskollen.Models.AidModel", b =>
                {
                    b.HasOne("Hjalpmedelskollen.Models.UnitModel", "UnitModel")
                        .WithMany()
                        .HasForeignKey("UnitModelId");

                    b.Navigation("UnitModel");
                });

            modelBuilder.Entity("Hjalpmedelskollen.Models.UnitModel", b =>
                {
                    b.HasOne("Hjalpmedelskollen.Models.InstitutionModel", "InstitutionModel")
                        .WithMany()
                        .HasForeignKey("InstitutionModelId");

                    b.Navigation("InstitutionModel");
                });
#pragma warning restore 612, 618
        }
    }
}
